context:
  name: httm
  version: "0.47.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/kimono-koans/${{ name }}/archive/${{ version }}.tar.gz
  sha256: 30174bbf0ee2c29590e2ae768393ca7ffc302f2a4b4bc481f363f8e51cfcf757

build:
  skip: win
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - httm --version

about:
  homepage: https://github.com/kimono-koans/httm
  summary: Interactive, file-level Time Machine-like tool for ZFS/btrfs/nilfs2 (and even Time Machine and Restic backups!)
  description: |
    The dream of a CLI Time Machine is still alive with httm.

    httm prints the size, date and corresponding locations of available unique versions (deduplicated by modify time and size) of files residing on snapshots, but can also be used interactively to select and restore files, even snapshot mounts by file! httm might change the way you use snapshots (because ZFS/BTRFS/NILFS2 aren't designed to find unique file versions) or the Time Machine concept (because httm is very fast!).
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/kimono-koans/httm

extra:
  recipe-maintainers:
    - pavelzw
